### ISSUE TITLE
PGI select type fails polymorphic pointer

### ISSUE THREAD

**Issue by dongli** [nncarlson/fortran-compiler-tests#2]
Dear @nncarlson, I am using your `map_any_type` module, and it works well with `gfortran`, but when switch to `pgf90` (18.4), I found select type block failed to check the real type of `class(*)` value. Here is a simple test:

```Fortran
program error_02

  use map_mod

  implicit none

  type foo_type
    integer i
  end type foo_type

  type(foo_type) foo
  type(map_type) map
  class(*), pointer :: bar

  call map%insert('foo', foo)

  bar => map%value('foo')

  select type (bar)
  type is (foo_type)
    print *, 'foo_type'
  class default
    print *, 'unknown'
  end select

end program error_02
```

The result `unknown`. I renamed the module name to `map_mod`, and I cannot found the origin repository, so I post the question here. >_<

**Comment by nncarlson** [comment]
Hi @dongli,

Yes the PGI compiler (and flang -- they are still mostly the same under the surface) has a lot of problems with F2003 code like the `map_any_type` module.  So I'm not surprised your example doesn't work, but I don't understand what your question or request is:

> [...] and I cannot found the origin repository, so I post the question here. 

Are you wanting to add a pgi bug test case to this repo?  Or just pointing me to a problem?

**Comment by dongli** [comment]
@nncarlson Thanks a lot! I just want to report a similar problem with PGI compiler. You are free to close this comment.

**Comment by dongli** [comment]
I have rewrite a [hash table module](https://github.com/dongli/fortran-container) and comply with the strict limits of PGI. What a nightmare to use PGI!
