### ISSUE TITLE
failing test cases

### ISSUE THREAD

**Issue by Sameeranjoshi** [nncarlson/fortran-compiler-tests#6]
I found some cases to fail, how do I solve that issue?

Total Test time (real) =   3.53 sec

The following tests FAILED:
	  1 - flang-20190512a-run (Failed)
	  3 - flang-20190511b-run (Failed)
	  4 - flang-20190511c-run (Failed)
	  5 - flang-20190506b-obj (Failed)
	  6 - flang-20190506c-obj (Failed)
	  7 - flang-20190505a-run (Failed)
	  8 - flang-20190504a-exe (Failed)
	  9 - flang-20190504a-run (Not Run)
	 10 - flang-20190504b-run (Failed)
	 11 - flang-20190504c-run (Failed)
	 12 - flang-20190503a-run (Failed)
	 13 - flang-20190503b-run (Failed)
	 17 - flang-20171123a-obj (Failed)
	 18 - flang-20171123b-obj (Failed)
	 21 - flang-20171122c-run (Failed)
	 24 - flang-20171122f-run (Failed)
	 25 - flang-20171122g-run (Failed)
	 32 - flang-20170924c-run (Failed)
Errors while running CTest

**Comment by nncarlson** [comment]
All the test cases in this repo were written to expose bugs in the respective compilers. Some compiler bugs have been fixed (those tests pass), while others have not. Those are the failing flang tests you see. Unless you are a flang compiler developer, you or I can't "solve" the issue; that's up to the flang developers. But these issues have been reported to flang.  The comments at the top of each source file have a link to the corresponding issue in their issue tracker.
