### ISSUE TITLE
add topics testsuite and test-suite

### ISSUE THREAD

**Issue by Beliavsky** [nncarlson/fortran-compiler-tests#8]
Please consider adding the topics testsuite and test-suite in the About section.

**Comment by nncarlson** [comment]
@Beliavsky was this meant for fortran-lang/stdlib?

**Comment by Beliavsky** [comment]
No, I think the topics are relevant for this repo. It would like something like the About section of https://github.com/mbdevpl/nas-parallel-benchmarks .

**Comment by nncarlson** [comment]
It finally clicked what you were talking about. Done. Thanks for the suggestion!
